apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    tier: cache
    app: redis
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: cache
      app: redis
  template:
    metadata:
      name: redis
      labels:
        tier: cache
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
          - containerPort: 6379