apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: vote
spec:
  type: NodePort
  selector:
    tier: frontend
    app: result-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081