apiVersion: v1
kind: Service
metadata:
  name: voting-service
  namespace: vote
spec:
  type: NodePort
  selector:
    tier: frontend
    app: voting-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080