apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    tier: frontend
    app: voting-app
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
      app: voting-app
  template:
    metadata:
      name: voting-app
      labels:
        tier: frontend
        app: voting-app
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
        ports:
          - containerPort: 80
    